name: campousia
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  location: ^4.4.0


  flutter_map: ^3.1.0
  latlong2: ^0.8.0


  flutter_offline: ^2.1.0
  internet_connection_checker: ^0.0.1+4
  permission_handler: ^10.2.0


  firebase_core: ^2.1.0
  cloud_firestore: ^4.0.2
  firebase_database: ^10.0.2
  firebase_auth: ^4.0.2

  carousel_slider: ^4.2.1
  favorite_button: ^0.0.4
  url_launcher: ^6.1.9







dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

dependency_overrides:

flutter:

  uses-material-design: true
